# Example YAML config file


# Maximum number of worker threads.  0 or remove for unlimited
max_threads : 40

# Packages to search for controllers in.
# packages are searched recursively
controller_packages:
   - com.trendrr.strest.examples
   # this controller adds websocket support.  remove to not allow websocket connections.
   - com.trendrr.strest.server.websocket
   # This controller serves files that are in the static directory
   - com.trendrr.strest.server.controllers.StaticFileController
   
# Any filters to be executed on every invocation.
# these must implement the StrestControllerFilter class
filters:
   # Leave this filter if you wish to use the "requiredParams" part of the annotation.
   - com.trendrr.strest.server.filters.RequiredParamsFilter 
   
   
   
# This section configures the ssl listener.
# ssl:
#    port: 8001
#    keystore: /home/username/keystore.jks
#    keystore_password: strest
#    certificate_password: strest

# Configuration of the default listener (i.e. regular http/strest)
default:
   port: 8000

# Configuration for the optional Templating available from TemplateRenderer
templates:
   base_dir : templates
   cache_timeout : 10000 #10 seconds

   
# Configuration for the Flash Socket Policy server.  this will serve the
# the flash socket policy so you can use the flash websocket bridge(allows
# websocket connections for browsers that don't support websockets
flashsocketpolicy:
   port : 843 # ONly change if you are doing some internal port routing, flash looks on port 843 by default